<template>
  <div class="row my-5">
    <div class="col-12 rows just-cen">
      <h1 class = ' d-inline-block p-3 rounded fw-bold'>4 Things I
      <span class = 'position-relative' style = 'transition:all 500ms' ref='love'>Loved
      <svg ref='love_svg' xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" class="opacity-none mb-1 fs-3 bi bi-balloon-heart-fill" viewBox="0 0 16 16">
<path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314"/>
</svg>
      </span>
      </h1>
    </div>
    <div class="col-12 rows just-cen">
      <h3
      :style ="{
      opacity : world()
      }"
      class = 'f-mute border-bottom border-dark pb-3'>In the world</h3>
    </div>
  </div>
  <Drawing></Drawing>
  <p>{{world()}}</p>
</template>

<script setup>
  import {ref} from 'vue'
  import {useScroll} from '../composable/scroll.js'
  import Drawing from './Body/Drawing'
  
  const {get_value : world, scroll} = useScroll(500,50,{callback : change_color})
  
  const love = ref(null)
  const love_svg = ref(null)
  
  //Cannot access 'change_color' before initialization
  const change_cowlor=()=>{
    love.value.style.color = 'crimson'
    love_svg.value.style.opacity = '1'
    love_svg.value.style.animation = 'wobble-hor-bottom 1s linear both'
  }
  
  function change_color(){
    love.value.style.color = 'crimson'
    love_svg.value.style.opacity = '1'
    love_svg.value.style.animation = 'scale-up-ver-top 500ms both'

  }
  
  
  
</script>

<style>
    .bg-shade{
  background-color : var(--shade)
  }
  
  .f-mute{
    color : var(--f-mute);
  }
  
  .opacity-none{
    opacity: 0;
  }
  
.scale-up-ver-top{animation:scale-up-ver-top .4s cubic-bezier(.39,.575,.565,1.000) both}

/* ----------------------------------------------
 * Generated by Animista on 2024-6-20 17:26:57
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

@keyframes scale-up-ver-top{0%{transform:scaleY(.4);transform-origin:100% 0}100%{transform:scaleY(1);transform-origin:100% 0}}

</style>